name: mobile_assessment
description: Irecharge mobile team assessment

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  skeletonizer: ^2.0.1
  path: ^1.9.1
  sqflite: ^2.4.2
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.3

#flutter_icons:
#  ios: true
#  android: true
#  image_path_ios: 'assets/images/logo_transparent.png'
#  image_path_android: 'assets/images/logo_transparent.png'

flutter:

  uses-material-design: true

  assets:
    - assets/
